### ISSUE TITLE
Cannot see the NFT description 

### ISSUE THREAD

**Issue by terzai** [ElrondNetwork/api.elrond.com#125]
I'm trying to get  data from the field 'Description' during the minting but I cannot find it through the api endpoint. Such as https://devnet-api.elrond.com/accounts/erd143lecehpnn9tuq89aw09zqfpxzwyermezrwh69877qguzpt3h4eszq6pzp/nfts/COLFIELD-40fa45-04.

Could it be encoded in the attribute 'Metada' ? If so how do we read it ?

Thank you

**Comment by tanghel** [comment]
Hello!

You need to base64 decode the "attributes" field:
dGFnczpsb2NhdGlvbjpVU0EsZXllc19jb2xvcjpibHVlLGpvYjpjb2RlcjttZXRhZGF0YTpRbVRGRnBuMXJjRFEyQWdXVzg3TFd0NmhDOUNwYUdtcEtIR1p0RUdHaThtejRO => tags:location:USA,eyes_color:blue,job:coder;metadata:QmTFFpn1rcDQ2AgWW87LWt6hC9CpaGmpKHGZtEGGi8mz4N

What appears after "metadata:" is an ipfs url, that can be accessed as such:
https://ipfs.io/ipfs/QmTFFpn1rcDQ2AgWW87LWt6hC9CpaGmpKHGZtEGGi8mz4N

In the returned JSON you will find the description.

We are already doing the heavy lifting regarding this, but we have some temporary issues regarding how we access ipfs. Once our internal ipfs redirect works properly, you will have a "metadata" field inside the nft with the description, fileName, etc.
