### ISSUE TITLE
Numbers of Tokens header vs Tab on mainnet https://explorer.elrond.com/

### ISSUE THREAD

**Issue by elrondex** [ElrondNetwork/api.elrond.com#271]
![image](https://user-images.githubusercontent.com/87403416/140626337-54d24e9d-7b1e-4bb8-8c43-05976448baa1.png)

**Comment by tanghel** [comment]
This is a front-end issue, since we display also NFTs of type MetaESDT as ESDT Tokens. it has been reported and will be fixed

**Comment by elrondex** [comment]
Thanks for report this!

@elrondex
