### ISSUE TITLE
Incorrect MEX Supply vs accounts/sc ammounts on testnet https://testnet-explorer.elrond.com/

### ISSUE THREAD

**Issue by elrondex** [ElrondNetwork/api.elrond.com#272]
![image](https://user-images.githubusercontent.com/87403416/140626431-f5db471a-5700-4c46-9279-9d84a3d52086.png)

**Comment by elrondex** [comment]
Same problem on mainnet https://explorer.elrond.com/tokens/WEGLD-6823c1/accounts

![image](https://user-images.githubusercontent.com/87403416/140626699-f734bbfe-09c7-4ac8-858b-a156678ecc98.png)

![image](https://user-images.githubusercontent.com/87403416/140626718-26a8cad9-c2f7-4086-862c-315f2bb5cdb6.png)

**Comment by tanghel** [comment]
<img width="674" alt="Screen Shot 2021-11-08 at 12 36 54" src="https://user-images.githubusercontent.com/4201606/140728360-d8812915-5f3f-4bfc-8993-2b50ed5fc6c8.png">
<img width="524" alt="Screen Shot 2021-11-08 at 12 38 35" src="https://user-images.githubusercontent.com/4201606/140728372-8a38d6d1-d8eb-4828-bfd6-ee670a681ebb.png">

The API returns correct amounts that add up. this is a front-end issue and has been reported internally

**Comment by tanghel** [comment]
Update: this is actually a javascript issue, since there are precision issues with handling Numbers. Here is an example in Google Chrome's javascript console:

![image](https://user-images.githubusercontent.com/4201606/140736452-5893926e-2c18-4189-91a2-f1697e826dc4.png)

The value 
0.60395483429230088 
when assigned to a Number, actually has the value
0.6039548342923009

**Comment by elrondex** [comment]
@tanghel Thanks for update.
On server side balance and supply is stored as string and sum is done with BigInt, this looks good for me.
In that case client need to find better way to convert to decimal number (Bigdecimal or similar)

Thanks for clarification!
@elrondex

**Comment by tanghel** [comment]
The client seems to be fine. The numbers indeed add up if you manually add them up, but not in a javascript console :)

Glad to help!
