### ISSUE TITLE
[BUG] royalties missing from GET /nfts/{indentifier}

### ISSUE THREAD

**Issue by mrazvanalex** [ElrondNetwork/api.elrond.com#273]
Retrieving an NFT via it's identifier using the /nfts/{identifier} route does not return a `royalties` property as stated in the model.

Example Call:
```https://devnet-api.elrond.com/nfts/KEOUF-b9f0a9-01```

Note that there is no royalties on the received model.

**Comment by tanghel** [comment]
In the case of this particular NFT, the royalties are 0:
https://devnet-gateway.elrond.com/address/erd17frjmjj93klz0w9gh0xj76atp8lk7h2k4uhawe8yp5g0rusprn0qm7n49c/nft/KEOUF-b9f0a9/nonce/01

Our cleanup function does not return 0 values, and this is something that we might consider in the future to improve. If the royalties are greater than 0, they should be reflected in the response

**Comment by mrazvanalex** [comment]
Hi! This issue seems to be existent also on NFTs that have a non-zero royalty value.

Here is a testnet example:
**ASD-7d08c3-01**

https://isengardappapidev.azurewebsites.net/Nfts/ASD-7d08c3-01

![image](https://user-images.githubusercontent.com/6265028/144747574-7fd42c0b-3c76-43f9-ba92-540f00109237.png)

But on the address/{address}/nft/{nftId} it works.
![image](https://user-images.githubusercontent.com/6265028/144747598-a507a687-1595-4038-bea0-8811d83e2614.png)
