### ISSUE TITLE
Can't retrieve NFT attributes created from SC on the API

### ISSUE THREAD

**Issue by Keouf** [ElrondNetwork/api.elrond.com#276]
Hi,

I tried to mint some NFT from a SC but it seems that it broke the attributes.

```
#[derive(TypeAbi, TopEncode, TopDecode)]
 pub struct AttributesNFT {
    attr: u64,
 }

 let attributes = AttributesNFT {
    number: 5u64,
 };

 let nft_nonce = self.send().esdt_nft_create(
   &token, 
   &amount_one, 
   &name,
   &royalties, 
   &hash, 
   &attributes, 
   &uris 
 );
```

I keep my code as simple as possible.

All the attributes result retrieve from the /nfts/{identifier} looks like : "AAAAAAAAAE=" 

To see if my previous code work I added the following code after the mint.

      let token_info = self.blockchain().get_esdt_token_data(
            &self.blockchain().get_sc_address(),
            &self.nft_token_id().get(),
            nft_nonce,
        );
        
        let decoded_attr = token_info.decode_attributes::<AttributesNFT>()?;

        require!(attributes.attr == decoded_attr.attr, "attr not the same");

I go throught the require, meaning that my nft have the right attr.

Here is the last NFT I mint on the devnet with the problem.
TATTR-bf65ea-01

**Comment by tanghel** [comment]
The base64 attributes for the 'TATTR-bf65ea-01 ' NFT are: AAAAAAAAAAMAAAAAAAAABQ==
https://devnet-api.elrond.com/nfts/TATTR-bf65ea-01

The same information is also available on the gateway:
https://devnet-gateway.elrond.com/address/erd17frjmjj93klz0w9gh0xj76atp8lk7h2k4uhawe8yp5g0rusprn0qm7n49c/nft/TATTR-bf65ea/nonce/01

When decoding this value to hex, I get value '3' as u64 and a '5' as u64.

This is not an API issue
