### ISSUE TITLE
I want to be able to get NFTs/Collections by Name

### ISSUE THREAD

**Issue by ciro247** [ElrondNetwork/api.elrond.com#298]
Hello, 

I'm trying to return some NFTs and Collections from your API by the `Name ` field and I see no way to do that.
I need to have that functionality in order to have a search working for my UI.

Can you add a new query string param that would return all nfts/collections that have in the name a specified string?

Ex: when I call `https://devnet-api.elrond.com/nfts?name="asd"` I get all NFTs  that have `NFT.Name.Contains("asd") == true`

**Comment by tanghel** [comment]
Hi! you can use the search endpoint as follows: https://devnet-api.elrond.com/nfts?search=hello

We do not yet have a name-specific search, but I think this coluld do the trick for you
