### ISSUE TITLE
/accounts endpoint has incorrect limit checking

### ISSUE THREAD

**Issue by astralmaster** [ElrondNetwork/api.elrond.com#324]
The value of the parameters `from `and `size` for the `/account` endpoint are summed for some reason and if the result exceeds 10000 an error is returned complaining that the sum of these parameters must be less than 10000. 
If I want to retrieve accounts from range [20000,25000] I cannot, since I would have to set the parameter 'from' to 20000 and `size` to 5000 and the sum would be greater than 10000.

**Comment by AlexandruPislariu** [comment]
Hello!
This is due to a limitation of ElasticSearch as it only allows 10k results per request. If requesting from index 20k to 20.5k, it has to compute 20k items so it can find the 20k th element.
We will add support on our API to be able to return a larger window by using ES scroll API.

**Comment by astralmaster** [comment]
I see. Do you have an alternative way that allows retrieving more? eg. Does the gateway.elrond.com use the same tech under the hood?
