### ISSUE TITLE
src/endpoints/transactions/transaction.module.ts:3:30 - error TS2307: Cannot find module 'src/plugins/plugin.module' or its corresponding type declar ations.

### ISSUE THREAD

**Issue by evergreen-trading-systems** [ElrondNetwork/api.elrond.com#325]

**Comment by evergreen-trading-systems** [comment]
`npm run dev` fails

**Comment by AlexandruPislariu** [comment]
Hello!
This is due to our latest feature with using plugins to process and recognize different type of transactions.
Please make sure that you have latest version of application from our main or development branch.

**Comment by evergreen-trading-systems** [comment]
had to run `npm run init`
