### ISSUE TITLE
nfts/count : query params do not effect result

### ISSUE THREAD

**Issue by TheoSabattie** [ElrondNetwork/api.elrond.com#381]
Hello',

Adding query params does not effect the count result.
https://api.elrond.com/nfts/count?type=NonFungibleESDT
https://api.elrond.com/nfts/count?type=SemiFungibleESDT
https://api.elrond.com/nfts/count?type=MetaESDT
https://api.elrond.com/nfts/count

Always return 10000

Does the count stop on a maximum value for performance issue?
If so, can you specify it on the documentation?

**Comment by AlexandruPislariu** [comment]
Hi @TheoSabattie 
Thank you for reporting this issue. 
It is fixed within this [PR](https://github.com/ElrondNetwork/api.elrond.com/pull/383) and now the filters affect the count result.
