### ISSUE TITLE
Can't retrieve logs from /transactions endpoint

### ISSUE THREAD

**Issue by MWFIAE** [ElrondNetwork/api.elrond.com#420]
It seems like I can (no longer?) retrieve the smart contract event logs using the transactions endpoint:

Expect the following to work:
https://devnet-api.elrond.com/transactions?withOperations=true&withScResults=true&hashes=46cea958a6dacd5eacec9bce8743de19ec6be2a7d9e2c3d3cbdaf45790539385&fields=logs

The following does work so the data is generally available in the api:
https://devnet-api.elrond.com/transactions/46cea958a6dacd5eacec9bce8743de19ec6be2a7d9e2c3d3cbdaf45790539385?fields=logs

Any help would be appreciated :)

PS: Of course, my real use case involves more than just one transaction, I want to parse all transactions concerning our token.
PPS: The /tokens/:ident/transactions endpoint has the same shortcomings as the normal transactions endpoint, which means I also get no event logs

**Comment by tanghel** [comment]
solved with this PR:

https://github.com/ElrondNetwork/api.elrond.com/pull/422

you  need to set `withLogs=true` in the transaction list
