### ISSUE TITLE
NFTs metada not updated

### ISSUE THREAD

**Issue by wellbranding** [ElrondNetwork/api.elrond.com#433]
We changed the metada of the NFT using erdpy function, but the api.elrond does not show changes :(

The elrond gateway displays the updated value, but not the api. Is it the cache thing and it will updated eventually?

**Comment by tanghel** [comment]
we have a prepared a PR for this:
https://github.com/ElrondNetwork/api.elrond.com/pull/445

this is still pending testing, but we should merge this soon.

In the meantime, we have manually refreshed metadata for all NFTs where the attributes have been updated

**Comment by wellbranding** [comment]
When why does this NFT metada did not change? 

Decode the data from the gateway and you will get a different value, here is a link:

https://bit.ly/3oieH3o

Now, please check the on the api, 

https://bit.ly/3GgV3ed

You can see that the attribute Top is Banana, it should be a Bandana, like on the gateway.

**Comment by theadriann** [comment]
Having the PR already merged into the development, should this be working on devnet?

I also believe that this issue should be closed when the bug is not reproducing anymore on the mainnet (since this is still causing problems/confusions).

**Comment by theadriann** [comment]
Having the PR already merged into the development, should this be working on devnet?

I also believe that this issue should be closed when the bug is not reproducing anymore on the mainnet (since this is still causing problems/confusions).

@tanghel @LucianMincu
