### ISSUE TITLE
Differences in metadata and media generated on the NFT responses

### ISSUE THREAD

**Issue by juliancwirko** [ElrondNetwork/api.elrond.com#446]
I wonder why there are differences between responses on NFTs even in the same collection. Let's take two NFTs from the same collection on the devnet. This one is ok.

https://devnet-explorer.elrond.com/nfts/EROBOT-251416-12 

As you can see, it has a proper `media` object and a proper `metadata` object. This is why there is a preview when hovering over the assets.

But this one doesn't have that:

https://devnet-explorer.elrond.com/nfts/EROBOT-251416-0d

The `media` object has default values, and there is no `metadata` object at all.

They are from the same collection. The base CID is also the same: `QmeDxANT39K8UgQo4FXQxJGJYDXMUXggMVTMcUAZznNs6q` 

I've tried many combinations using CIDs without the file name, using CID v0 and v1, and I can't find the rule for that.
Is this a known bug, or do I not get something?

**Comment by AlexandruPislariu** [comment]
Hello! It is possible that your NFT couldn't trigger a process for media and metadata.
We have a cron job that process all NFTs daily and it seems that it solved your issue.
