### ISSUE TITLE
Account SC results endpoint not working properly.

### ISSUE THREAD

**Issue by paulpou69** [ElrondNetwork/api.elrond.com#456]
The "/accounts/<address>/sc-results" endpoint does is not working properly.
![image](https://user-images.githubusercontent.com/32978093/153079277-47ce7125-2991-4e77-88c1-3093673a7542.png)

In this image you can see that the receiver of the transaction is "erd14ud93aymz9u6f3vy4k3l9hsw4sdc9sc5hjvwtjhazfs6dake982sn94twp"

The transaction hash is "dfa70a468088caba3dfb743015c48f9f1dad689805f139caec38c8a6ad006247".

But as you can see, the hash is not in the sc-results.

![image](https://user-images.githubusercontent.com/32978093/153080286-9e0c7b41-2f16-44c5-90ac-0b7e688c9fd9.png)

I want to mention that the code that uses this endpoint works perfectly on the devnet and testnet.

**Comment by AlexandruPislariu** [comment]
Hello!
Thank you for reporting this issue. It was a indexer problem that was solved with a new version of indexer(devnet & testnet, mainnet will come soon).

I will close this issue since it is solved within this [PR](https://github.com/ElrondNetwork/api.elrond.com/pull/430) .
