### ISSUE TITLE
Request URI error creation

### ISSUE THREAD

**Issue by aoctavian** [ElrondNetwork/api.elrond.com#472]
Endpoints where a field is implemented as array[string] the API creates an incorrect URI which returns 'Internal server error 500'.

For example,
1. /accounts/{address}/nfts - 'tags' field => the output URL is: tags=TAG1&tags=TAG2 which returns 'Internal server error 500'
2. /nfts - 'tags' field is implemented with text-box where tags should be separated with comma -> this is working as expected

I believe everywhere where field is implemented with array[string] the API creates an incorrect URI.

**Comment by AlexandruPislariu** [comment]
Hello!
The tags field should be used as in swagger doc is written (with comma separated values) for example [/nfts?tags=Subcarpati,Music](https://api.elrond.com/nfts?tags=Subcarpati,Music)
