### ISSUE TITLE
Multi ESDT Transfer - Transaction Details

### ISSUE THREAD

**Issue by aoctavian** [ElrondNetwork/api.elrond.com#474]
The API is duplicating the operations of transaction **after a few seconds**.
Testing: Send a multi transfer esdt then refresh the page after few seconds. (In my case after ~25s on devnet)

https://devnet-explorer.elrond.com/transactions/f16e1757111ad3caf7558d664fcf63ec1c5ad77c244aaca16d92c6ce2f255270

**Comment by alexberce** [comment]
It happens with normal transfers on mainnet as well. It's showing the correct number of token operations for a few seconds (see picture) and then it adds 1 or 2 extra.

From what I noticed, it happens only with **ESDTNFTTransfer**


![Screenshot 2022-03-10 at 23 20 10](https://user-images.githubusercontent.com/9248169/157757620-c1a5511e-3b11-4f77-b19c-7356319ea331.png)

https://explorer.elrond.com/transactions/288dc8bdd296bcab2e08165df9d041adf2235d78c78d8801bf8984f2762faa12

**Comment by tanghel** [comment]
This issue has been fixed with the following PR:

https://github.com/ElrondNetwork/api.elrond.com/pull/527

thank you!
