### ISSUE TITLE
/accounts/{address}/nfts/count endpoint error

### ISSUE THREAD

**Issue by aoctavian** [ElrondNetwork/api.elrond.com#475]
‘collections’ field returns an unexpected number of NFTs

Details (DevNet):
Wallet NFTs:
   1. _OAGNFT-c14676_: 92x SFTs
   2. _TECOL-9f6df5_: 5x NFTs
Query: 
https://devnet-api.elrond.com/accounts/erd16nlhrnlm30qkpy8q52u95aaw0gjtx33xmlp62g5p4kj4mje04drq5y2tlw/nfts/count?collections=TECOL-9f6df5
returns **6** and should return **5**.

Other details:
https://devnet-api.elrond.com/accounts/erd16nlhrnlm30qkpy8q52u95aaw0gjtx33xmlp62g5p4kj4mje04drq5y2tlw/nfts?collections=TECOL-9f6df5
This returns an array with 5 NFTs which is correct.

**Comment by AlexandruPislariu** [comment]
Hello @aoctavian !
Thank you for your contribution, this is a good catch!
We have a fix in progress within this [PR](https://github.com/ElrondNetwork/api.elrond.com/pull/483).
