### ISSUE TITLE
Collection NFTs supply endpoint

### ISSUE THREAD

**Issue by aoctavian** [ElrondNetwork/api.elrond.com#476]
I believe an endpoint /collections/{identifier}/supply to get the number of NFTs/SFTs in the collection is very nice to have :).

**Comment by AlexandruPislariu** [comment]
Hello!
If you want to know the number of NFTs/SFTs in the collection you can use /nfts/count endpoint with collection parameter.
Here is an example: [https://api.elrond.com/nfts/count?collection=OGS-3f1408](https://api.elrond.com/nfts/count?collection=OGS-3f1408)
