### ISSUE TITLE
Token Identifier != Ticker

### ISSUE THREAD

**Issue by aoctavian** [ElrondNetwork/api.elrond.com#477]
For ESDTs like AERO/RIDE/WEGLD/LKMEX the API returns the Token Identifier and the Ticker correctly.
For a lot of other ESDTs both Testnet and Mainnet (tested by me) the Token Identifier is EQUAL to Ticker which is not correct and needs to be manipulated by the developers (even when using elrond-sdks (C# tested)).

**Comment by AlexandruPislariu** [comment]
For ESDT tokens that does not have assets in this [repo](https://github.com/ElrondNetwork/assets) it means that these tokens are not verified/approved by us and for this reason these tokens don't have a official ticker.
