### ISSUE TITLE
Impossible to fetch larger NFT accounts due to API limitations

### ISSUE THREAD

**Issue by borispoehland** [ElrondNetwork/api.elrond.com#490]
Hey guys,

I'm hosting an NFT explorer and because of your API it is impossible for me to make it right. Let me show you what I mean:

I would like to fetch people's NFTs lazy/in batches using the `from` parameter in `/accounts/{address}/nfts`. However, the `from` parameter isn't working, as seen in this images:
![Bildschirmfoto von 2022-02-24 13-24-41](https://user-images.githubusercontent.com/60541010/155523802-93a8e82f-262e-40c7-a775-2e1dc0ea6226.png)
![Bildschirmfoto von 2022-02-24 13-24-51](https://user-images.githubusercontent.com/60541010/155523805-746291ab-8dc1-4e5d-b464-99b2d3e75e91.png)

As you can see, `from` does not change anything about the result. This is the main issue. [Here](https://api.elrond.com/accounts/erd1y6jslrt584hwxczk2hvrezs4pet87936ttqhzx63lmzwsg8gmw2srqxv47/nfts?from=0) is the address I used.

That's why I decided that there is no way around but **fetching everything at once** (and splitting result on the frontend) for my use case.

But even there is an error. Currently, one can fetch at most 621 NFTs of somebody at a time:
![Bildschirmfoto von 2022-02-24 13-36-42](https://user-images.githubusercontent.com/60541010/155525449-f9718de7-4fee-4be5-846a-bdbc3b0c9e28.png)
![Bildschirmfoto von 2022-02-24 13-36-49](https://user-images.githubusercontent.com/60541010/155525452-d48c1a1c-f36a-4d78-bb3a-a016bdebcc4b.png)

Everything larger results in an empty array as response. [Here](https://api.elrond.com/accounts/erd1qqqqqqqqqqqqqpgq6wegs2xkypfpync8mn2sa5cmpqjlvrhwz5nqgepyg8/nfts?size=621) is the address I used.

These 2 things combined make it impossible for me to fetch accounts with >621 NFTs. Splitting/Lazy Loading isn't possible because of `from`, and fetching everything at once isn't possible due to your API returning an empty array when the `size` is larger than 621.

Given these circumstances, how is it possible for me to consistently fetch NFT accounts?

Thanks and best regards,
Boris Pöhland

**Comment by CatalinFaurPaul** [comment]
Hi Boris, thank you for founding this issue. We fixed this bug with #502 and now we are able to fetch a much larger numbers of nfts ( >621).
Here you can see that the endpoint returns a much larger numbers of nfts [Request](https://api.elrond.com/accounts/erd1qqqqqqqqqqqqqpgq6wegs2xkypfpync8mn2sa5cmpqjlvrhwz5nqgepyg8/nfts?size=1000).

Thanks and best regards
