### ISSUE TITLE
please add a license

### ISSUE THREAD

**Issue by muhlemmer** [ElrondNetwork/api.elrond.com#520]
There is no license that grants persons to use the code in this repository.

> [**No License**](https://choosealicense.com/no-permission/)
> 
> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. **Once the work has other contributors (each a copyright holder), “nobody” starts including you.**

**Comment by tanghel** [comment]
fixed! thank you!
