### ISSUE TITLE
Owner missing from API call

### ISSUE THREAD

**Issue by Rollo98** [ElrondNetwork/api.elrond.com#522]
If I try to call the following
`https://api.elrond.com/nfts?from=0&size=1&withOwner=true&type=NonFungibleESDT` - with `from=0` I get the owner
On the other side if I call
`https://api.elrond.com/nfts?from=1&size=1&withOwner=true&type=NonFungibleESDT` - with `from=1` ( or whatever number other then 0 ) I do not get the owner

Also does not work with collection code. I've tried with `ESCU-ee0923`

**Comment by razvanstatescu** [comment]
Same problem here. Was working correctly recently. Does anyone know a workaround to be able to determine the owner of each NFT in a specific collection? Thanks!

**Comment by Rollo98** [comment]
The one solution I came up with was to use the `nfts/{identifier}` path. Generate a 10.000 hex numbers array. 10.000 API calls later you got an object with owners and what nfts they have. You have to do call each 1.2 seconds for the server to not block you :)

**Comment by tanghel** [comment]
This has been fixed with the following PR: https://github.com/ElrondNetwork/api.elrond.com/pull/531

Will be deployed shortly on mainnet
