### ISSUE TITLE
NftController_getNftOwners - doesn't consider from parameter

### ISSUE THREAD

**Issue by dan-merlea** [ElrondNetwork/api.elrond.com#550]
There is an issue with api.elrond.com - NftController_getNftOwners - doesn't consider from parameter

Demo: 

https://api.elrond.com/nfts/KROGAN-54c361/owners?from=0
https://api.elrond.com/nfts/KROGAN-54c361/owners?from=24

Same result.

**Comment by tanghel** [comment]
The issue should be fixed with the following PR: https://github.com/ElrondNetwork/api.elrond.com/pull/551

Please make sure you use the correct endpoint for getting owners

**Comment by dan-merlea** [comment]
Yes, I managed to solve what I needed with this endpoint. 
https://api.elrond.com/nfts?collection=KROGAN-54c361&withOwner=true

But there is a bigger limitation since I can only retrieve 100 elements, while with 
https://api.elrond.com/nfts/KROGAN-54c361/owners?from=0
I can retrieve up to 1000.

Good to know that will be fixed though.
