### ISSUE TITLE
Getting owners through endpoint is not stable

### ISSUE THREAD

**Issue by aoctavian** [ElrondNetwork/api.elrond.com#558]
Getting owners through endpoint /collections/{collection}/nfts?from+size+withOwners is returning different values almost each run.

This is the code I'm using (just ignore the auto-conversion for code from github):

class NFT
{
    public string Identifier { get; set; }
    public string Owner { get; set; }
}

private async void GetOwners_Click(object sender, EventArgs e)
{
    List<NFT> nfts = new List<NFT>();
    int from = 0;
    while(true)
    {
        var req = await new HttpClient().GetAsync($"https://api.elrond.com/collections/NEONCYBERS-1442a8/nfts?from={from}&size=100&withOwner=true");
        string content = await req.Content.ReadAsStringAsync();
        var respNfts = JsonConvert.DeserializeObject<List<NFT>>(content);
        if (respNfts.Count == 0)
            break;

        nfts.AddRange(respNfts);
        from += 100;
    }
    var owners = nfts.Select(n => n.Owner).Distinct();
    var identifiers = nfts.Select(n => n.Identifier).Distinct();

    StreamWriter sw = new StreamWriter($"{DateTime.Now.ToString("dd.MM.yyyy HH.mm.ss")}.txt");
    sw.WriteLine($"Total Owners: {owners.Count()}");
    sw.WriteLine($"Total Identifiers: {identifiers.Count()}");
    sw.WriteLine($"Total Results: {nfts.Count}");
    sw.WriteLine(JsonConvert.SerializeObject(nfts.OrderBy(n=>n.Identifier), Newtonsoft.Json.Formatting.Indented));
}

In 5 runs the results are the following:
1. Total Owners: 446
    Total Identifiers: 1480
    Total Results: 1500
2. Total Owners: 449
   Total Identifiers: 1490
   Total Results: 1500
3. Total Owners: 454
   Total Identifiers: 1499
   Total Results: 1500
4. Total Owners: 454
   Total Identifiers: 1500
   Total Results: 1500
5. Total Owners: 454
    Total Identifiers: 1500
    Total Results: 1500

[446, 1480, 1500.txt](https://github.com/ElrondNetwork/api.elrond.com/files/8350277/446.1480.1500.txt)
[449, 1490, 1500.txt](https://github.com/ElrondNetwork/api.elrond.com/files/8350278/449.1490.1500.txt)
[454, 1499, 1500.txt](https://github.com/ElrondNetwork/api.elrond.com/files/8350279/454.1499.1500.txt)
[454, 1500, 1500.txt](https://github.com/ElrondNetwork/api.elrond.com/files/8350280/454.1500.1500.txt)
[454, 1500, 1500_2.txt](https://github.com/ElrondNetwork/api.elrond.com/files/8350281/454.1500.1500_2.txt)

So,
- The total results is 1500 which is fine because there are 1500 NFTs in the collection.
- The total number of **distinct owners** is different in runs
- The total number of **distinct identifiers** is different in runs

This is a major issue, the API returns duplicate 'identifier' results and we cannot get the owners.
Observed: The errors seem to be like in the middle of the 100 results so I guess is not a pagination issue.

**Comment by tanghel** [comment]
Hello!

In order to achieve the desired results, my suggestion would be to use the `accountsesdt` collection from https://index.elrond.com, filtered by collection.

In that way, you can request up to 10.000 items at a time and beyond 10.000 elements you can use scroll API
