### ISSUE TITLE
/account/{address}/collections not working as expected

### ISSUE THREAD

**Issue by borispoehland** [ElrondNetwork/api.elrond.com#563]
Hello together,

I was looking for an endpoint that returns me the collections that an address holds. Best case would even be choosing how many of the NFTs of that collection one wants to display, but I think this is already implemented with the `nftSize` query param of that endpoint. 

So for example, this is how a request-response would look like:
Request: https://api.elrond.com/accounts/{address}/collections?nftSize=3
Response: 
```
{
  'REALM-579543': [
      {
          /* nft object 1 */
      },
      {
          /* nft object 2 */
      },
      {
          /* nft object 3 */
      },
  ],
  'OGS-3f1408': [
      {
          /* nft object 1 */
      },
      {
          /* nft object 2 */
      },
      {
          /* nft object 3 */
      },
  ],
},
```

I would already be satisfied with a string array of collection tickers as response, in that case `['REALM-579543', 'OGS-3f1408']`

The problem is, that whatever address I lookup, I always get an empty response.

I think this functionality is important to be included. Otherwise, in order to lookup what collections a wallet has, one has to fetch all NFTs of that wallet, which is very expensive.

Thanks for your help and I hope that the endpoint will be fixed!

Best regards,
Boris

**Comment by saoirsefree** [comment]
+1

**Comment by tanghel** [comment]
Hello!

Indeed, we do not have the option right now to fetch the distinct nft collection that an account owns.

We will have to first update the indexer to achieve that goal. We will discuss this internally for including this functionality in the upcoming indexer, but this may take a while.

We will also explore some clever ways of querying the indexer without having to wait for the update, but the success of this is not guaranteed.

In the meantime, you can use the `fields` parameter to limit the output of the result (not optimal, but helps a bit with response size):
https://api.elrond.com/accounts/erd1qqqqqqqqqqqqqpgqh438d42h9ltlqgpmjxc3srxafnx383n5kagq6hynlu/nfts?fields=collection&size=10000

**Comment by tanghel** [comment]
We have now implemented this change as following:

https://api.elrond.com/accounts/erd1qqqqqqqqqqqqqpgqh438d42h9ltlqgpmjxc3srxafnx383n5kagq6hynlu/collections returns 1 element (now returns distinct collections of the nfts in the balance)

https://api.elrond.com/accounts/erd1qqqqqqqqqqqqqpgqh438d42h9ltlqgpmjxc3srxafnx383n5kagq6hynlu/roles/collections returns 0 elements (it was the previous account collections endpoint)
