### ISSUE TITLE
sum aggregation

### ISSUE THREAD

**Issue by pislaru** [ElrondNetwork/api.elrond.com#579]
Hi.

I'm trying to calculate the sum of all transactions of a certain type.
(Basically i filter the transactions by the data field and i want the sum of the 'value' field)
Buy i'm receiving the following error.

Any idea?

![2022-04-10 19 54 49](https://user-images.githubusercontent.com/32090870/162630656-18280a5e-11c9-4a28-8142-a7264e8986ea.jpg)

**Comment by pislaru** [comment]
@tanghel

**Comment by tanghel** [comment]
Hello, unfortunately this is not possible with the way we index the data. You must scroll through all of them and sum them up manually
