### ISSUE TITLE
/accounts/{address}/collections returns empty response if filter canCreate is set

### ISSUE THREAD

**Issue by VladimirAndrianov96** [ElrondNetwork/api.elrond.com#585]
If any value is chosen for "canCreate" filter, the returned response is always empty [], without this option set I receive correct values for collections with canCreate "false" and "true" value.
1) filter set to false
![image](https://user-images.githubusercontent.com/15718242/163714268-eef5ccf9-cffa-46cb-8871-e3f1ce1b8ba7.png)
2) filter set to true
![image](https://user-images.githubusercontent.com/15718242/163714272-5f487768-f825-40df-8971-eb01af5b039e.png)
3) no filtering option is set
![image](https://user-images.githubusercontent.com/15718242/163714276-c410cba4-0527-4837-83fd-5b86ca41085d.png)

**Comment by tanghel** [comment]
Hello!

This issue is caused by the fact that we have temporarily reverted the underlying elasticsearch to an older version. We expect it to be back today or tomorrow the latest

**Comment by ElrondWorld** [comment]
> 

Hey @tanghel , any updates on this yet?

**Comment by VladimirAndrianov96** [comment]
the problem is still there

**Comment by tanghel** [comment]
Sorry guys, some unforeseen issues appeared in the meantime and we will have to delay the new indexer for a few more days.

Thank you for your patience!

🙏

**Comment by ElrondWorld** [comment]
> Sorry guys, some unforeseen issues appeared in the meantime and we will have to delay the new indexer for a few more days.
> 
> Thank you for your patience!
> 
> 🙏

Hey @tanghel any updates for us yet please?

**Comment by ElrondWorld** [comment]
Good day,
@tanghel are there any updates yet,
is there a way to escalate this issue?

Thanks in advance

**Comment by tanghel** [comment]
Sorry for the delay!

We have switched also api.elrond.com in the meantime to the new indexer.

For as long as you use `&source=elastic` parameter, it should work fine on all environments now
