### ISSUE TITLE
LKMEX vs LP LKMEX-EGLD

### ISSUE THREAD

**Issue by bogdanIuga** [ElrondNetwork/api.elrond.com#587]
Hello, it's not necessary an issue but I couldn't find anything related to how you make the difference between these 2. They share the same collection, the same difference is the attributes property.

Is it a bug? Even though in maiar.exchange it sets them correctly. 

A reference on how I could distinguish them would be awesome. Couldn't find anything in docs.elrond.com 

![image](https://user-images.githubusercontent.com/26706013/164243088-fb82dd22-e010-4f23-8aa3-63cc4e91cbbb.png)

https://api.elrond.com/accounts/erd1793tlju2h2ps3f5klqy3rkyj88h9njgx40ys5pkyz0cufhecxhrsenyyam/nfts?collections=EGLDMEXF-5bcc57,EGLDUSDCF-8600f8,MEXFARM-e7af52,EGLDMEXF-a4d81e,EGLDUSDCF-e3e01e,MEXFARM-5d1dbb,EGLDRIDEF-6c5d7c,EGLDMEXFL-ef2065,EGLDUSDCFL-f0031c,MEXFARML-28d646,EGLDRIDEFL-74b819,MEXRIDEF-bf0320,METARIDE-a68897,METARIDELK-bd8cda,LKFARM-9d1ea8&size=600

Thanks in advance.

Keep up the good work! :D

**Comment by bogdan-rosianu** [comment]
You can find the contained fields of the attributes here:
https://github.com/ElrondNetwork/sc-dex-rs/blob/fa73845ac4c1baf594efa99286f93dfbaad550b9/common/common_structs/src/lib.rs#L65

**Comment by tanghel** [comment]
To add to this, the attributes are encoded in base64 using a binary formatter, and you can use erdjs to decode them.

Since this is not an issue directly related to api.elrond.com, I will close this issue

🔥
