### ISSUE TITLE
/account/{address}/nfts doesn't return timestamp

### ISSUE THREAD

**Issue by borispoehland** [ElrondNetwork/api.elrond.com#590]
Good morning! :)

In the response description of the `/account/{address}/nfts` endpoint is a timestamp:
![Screenshot_20220423-082159.jpg](https://user-images.githubusercontent.com/60541010/164882771-3312e5f5-6478-40bf-b2a9-03dbe8d6bffe.jpg)

However, when actually querying the endpoint, the `timestamp` is not returned.

I assume the timestamp is the time at which the NFT arrived in one's wallet, right?

Because it would be cool to have this information, so that NFTs can be sorted by "Newest first".

Thanks for your help

Boris

**Comment by tanghel** [comment]
Hello!

By default, the NFT list is returned from the gateway, where we do not have this type of information

To get timestamp, you can call `/accounts/:account/nfts?source=elastic` which will return data from elasticsearch, which contains timestamp

**Comment by borispoehland** [comment]
@tanghel I just tried this out and it doesn't return me the timestamps...

**Comment by tanghel** [comment]
Indeed, the public api is not yet targeting the new indexer. Will be available soon-ish, in 1-2 weeks

**Comment by tanghel** [comment]
Happened sooner than initially anticipated! 

Timestamp is now available if the `source=elastic` parameter is set

🔥
