### ISSUE TITLE
/transfers route return error 501

### ISSUE THREAD

**Issue by dotmobo** [ElrondNetwork/api.elrond.com#597]
Hi
The route : 

https://api.elrond.com/accounts/{address}/transfers?from=0&size=25

return an error : 
`
{"statusCode":501,"message":"Endpoint not live yet"}`

**Comment by tanghel** [comment]
the public api still has the "v2" indexer
We are working towards providing the "v3" indexer with support for the transfers endpoint in the coming days

**Comment by tanghel** [comment]
It is now live

🔥
