### ISSUE TITLE
/tokens with identifier returns different responses

### ISSUE THREAD

**Issue by bogdanIuga** [ElrondNetwork/api.elrond.com#599]
I'm making the same request: https://api.elrond.com/tokens?identifiers=ZPAY-247875 multiple times, at a distance of 1-2 seconds and i get different responses...

the difference is that "**minted**" property is replace with "**supply**" and "**circulatingSupply**"

Response 1:
[
  {
    "identifier": "ZPAY-247875",
    "name": "ZoidPay",
    "ticker": "ZPAY",
    "owner": "erd136kalm60ndyyps7paexvz38pf09f58f7nzqg8tw60p9pq7ygyspsx6ux89",
    "**minted**": "700000000000000000000000000",
    "burnt": "0",
    "decimals": 18,
    "isPaused": false,
    "assets": {
      "website": "https://www.zoidpay.com",
      "description": "Shop Anything from Anywhere with Crypto",
      "social": {
        "email": "hello@zoidpay.com",
        "blog": "https://medium.com/zoidcoin-network",
        "twitter": "https://twitter.com/zoidpay",
        "whitepaper": "https://drive.google.com/file/d/1ZRwyAikfe22v9treyjeJoKi83W5U0y1j/view?usp=sharing",
        "coinmarketcap": "https://coinmarketcap.com/currencies/zoidpay/",
        "coingecko": "https://www.coingecko.com/en/coins/zoid-pay"
      },
      "status": "active",
      "pngUrl": "https://media.elrond.com/tokens/asset/ZPAY-247875/logo.png",
      "svgUrl": "https://media.elrond.com/tokens/asset/ZPAY-247875/logo.svg"
    },
    "transactions": 68622,
    "accounts": 36588,
    "canUpgrade": true,
    "canMint": false,
    "canBurn": false,
    "canChangeOwner": true,
    "canPause": false,
    "canFreeze": false,
    "canWipe": false
  }
]

Response 2:
[
  {
    "identifier": "ZPAY-247875",
    "name": "ZoidPay",
    "ticker": "ZPAY",
    "owner": "erd136kalm60ndyyps7paexvz38pf09f58f7nzqg8tw60p9pq7ygyspsx6ux89",
    "decimals": 18,
    "isPaused": false,
    "assets": {
      "website": "https://www.zoidpay.com",
      "description": "Shop Anything from Anywhere with Crypto",
      "social": {
        "email": "hello@zoidpay.com",
        "blog": "https://medium.com/zoidcoin-network",
        "twitter": "https://twitter.com/zoidpay",
        "whitepaper": "https://drive.google.com/file/d/1ZRwyAikfe22v9treyjeJoKi83W5U0y1j/view?usp=sharing",
        "coinmarketcap": "https://coinmarketcap.com/currencies/zoidpay/",
        "coingecko": "https://www.coingecko.com/en/coins/zoid-pay"
      },
      "status": "active",
      "pngUrl": "https://media.elrond.com/tokens/asset/ZPAY-247875/logo.png",
      "svgUrl": "https://media.elrond.com/tokens/asset/ZPAY-247875/logo.svg"
    },
    "transactions": 68622,
    "accounts": 36588,
    "canUpgrade": true,
    "canMint": false,
    "canBurn": false,
    "canChangeOwner": true,
    "canPause": false,
    "canFreeze": false,
    "canWipe": false,
    "**supply**": "700000000",
    "**circulatingSupply**": "700000000"
  }
]

I've hit a server with a bad deploy? :D

**Comment by tanghel** [comment]
indeed, there was an inconsistency, solved here: https://github.com/ElrondNetwork/api.elrond.com/pull/602

Thank you for reporting this! 🙏
