### ISSUE TITLE
URGENT https://api.elrond.com/nfts returns invalid data

### ISSUE THREAD

**Issue by zekdigital** [ElrondNetwork/api.elrond.com#623]
Hi.

https://api.elrond.com/nfts is returning invalid data.

Currently, for https://api.elrond.com/nfts/PASS-1c7c6a-51, the owner is shown as:
"owner":"erd17x84s53883pnfwx74lnr56dg2fkxg2mk8dcgsv3aywx70emcmf7sftt97k"

But if you look on https://explorer.elrond.com/nfts/PASS-1c7c6a-51, you get:
erd1adz0ud7q3edwv5de9suu6lcdz4lf4svje50vpplngkslhadvjmxqa0qwcr

I will attach pictures.
<img width="1436" alt="CleanShot 2022-05-10 at 16 21 16@2x" src="https://user-images.githubusercontent.com/105294178/167638197-98ab623c-2d6f-465d-84f6-600c98a38e29.png">
<img width="734" alt="CleanShot 2022-05-10 at 16 21 24@2x" src="https://user-images.githubusercontent.com/105294178/167638229-55e2fd95-8999-4136-8400-5eb005cc61e0.png">

What is correct and what is not?

**Comment by BalooSuperRareBears** [comment]
Hello,

I'm facing the same issue.

Collection NFT: **SRB-61daf7**
Collection NFT identifier: **SRB-61daf7-1e11**

Endpoint https://api.elrond.com/nfts/SRB-61daf7-1e11returns a SC Marketplace owner.

While, the same NFT identifier **SRB-61daf7-1e11** can be found in an erd wallet, check this endpoint: https://api.elrond.com/accounts/erd1qafz8ljqr8mksmjkdvxvcms0qcqe4nqzj6lw2pv5vjxr2xjsnxcqfcg85r/nfts?size=100&collections=SRB-61daf7


The same situation applies for this endpoint that shows the SC Marketplace as owner: https://api.elrond.com/collections/SRB-61daf7/nfts?withOwner=true&identifiers=SRB-61daf7-1e11


If it helps in any way, this endpoint shows 2 owners of the same NFT: https://api.elrond.com/nfts/SRB-61daf7-1e11/accounts

Thank you!

**Comment by tanghel** [comment]
@miiu96 indexing issue:
https://index.elrond.com/accountsesdt/_search?q=identifier:SRB-61daf7-1e11&default_operator=and returns 2 entries
https://index.elrond.com/accountsesdt/_search?q=identifier:PASS-1c7c6a-51&default_operator=and returns 2 entries

**Comment by miiu96** [comment]
Thank you for reporting this. We are working to fix this issue.

**Comment by tanghel** [comment]
In the meantime, we have a workaround on the API level that should fix the manifestation of this bug:

https://github.com/ElrondNetwork/api.elrond.com/pull/627

**Comment by tanghel** [comment]
It should be fixed now, it's deployed on mainnet

**Comment by BalooSuperRareBears** [comment]
Looks fine now, thank you!

This endpoint still returns 2 owners for the same NFT identifier:
https://api.elrond.com/nfts/SRB-61daf7-1e11/accounts

**Comment by tanghel** [comment]
yes, the endpoint still returns 2 owners, since the indexing bug is still there. will close the issue once @miiu96 confirms the indexing issue is fixed

🙏

**Comment by tanghel** [comment]
This issue has been fixed also at the indexer level, so I will close this issue
