### ISSUE TITLE
/transactions/{txHash} and /transaction?withOperations=true shows different amount of data

### ISSUE THREAD

**Issue by WIttyJudge** [ElrondNetwork/api.elrond.com#643]
Hi guys, 
I have noticed an issue.
Are there any differences between these two methods in terms of information about transaction?

```
/transaction/{txHash} 
```
and 
```
/transaction?miniBlockHash=hash?withLogs=true?withOperations=true?withScResults=true
```

The problem is when I use the first method, it returns 22 amount of the operations, but the second one returns 25.
I use this transaction: 89467b8d941a8b1db9b4e97a77b245f4ec3eed4b92bcf6723c447b629e49f4d9

Please, take a look:
@tanghel 
```
https://api.elrond.com/transactions?withLogs=true&withOperations=true&withScResults=true&miniBlockHash=d7fbec5a0ab83202804d7667daeb9c6f133dbffe465042379ff764f63ae7b5aa
```

```
https://api.elrond.com/transactions/89467b8d941a8b1db9b4e97a77b245f4ec3eed4b92bcf6723c447b629e49f4d9
```

**Comment by tanghel** [comment]
Thank you for reporting this!

It is fixed with the following PR: https://github.com/ElrondNetwork/api.elrond.com/pull/657

The problem resided through the fact that the id of the operation was not included, thus causing the trimOperations function to not remove 3 operations (hence the difference between 22 and 25)

🔥

**Comment by WIttyJudge** [comment]
Thank you. I found that issue and fixed in Bitquery fork as well. I have also added feature to read data by batch. E.g. at the moment it's possible to pass range of blocks 
and receive array of data, instead of making query for each block individisly.
