### ISSUE TITLE
Elrond API not populating NFT metadata even after days 

### ISSUE THREAD

**Issue by borispoehland** [ElrondNetwork/api.elrond.com#691]
Hello!

The way I understand the API output from the `/nft/{identifier}` endpoint is that you guys will query the IPFS of an NFT asynchronously, and then populate the `metadata` property of the NFT with the metadata you gathered from the `metadata:ipfsCID/fileName.json;` file.

Now, I launched an NFT collection a few days back, and only a few of the NFTs have the `metadata` property already.

How long will it take for you to populate the whole collection with the IPFS-Metadata? Or am I missing something?

Best and thanks,
Boris

**Comment by tanghel** [comment]
Hello,

usually it takes up to a minute, in rare situations up to 1h, and in ultra-rare situations it somehow isn't indexed at all.

We can take a look to see what went wrong there.

Could you please share the collection identifier so we can take a look at the logs?

**Comment by borispoehland** [comment]
Hey @tanghel, sure!

Our collection ticker is `SEAGULL-9746cc`

**Comment by borispoehland** [comment]
@tanghel maybe that helps:

When I call the metadata link of an NFT that has not been indexed yet, I get no response, or a 504 Gateway timeout after a minute or so. Here's an example:

https://ipfs.io/ipfs/QmVjKGquME6MS3pMBTUovsGHVr86UVWnRveysFyHNeBUdQ/2607.json

I thought this is normal for IPFS. Did I do anything wrong in the metadata upload perhaps?

Best

**Comment by tanghel** [comment]
Indeed, most likely because of the fact that the json file could not be downloaded. When testing out, I also get 504 gateway timeout.

Unfortunately, you can only add uris, and not edit existing ones, so maybe a clean approach would be to burn all nfts and re-create them with proper ipfs urls.

How were these NFTs created? If you created them using an NFT marketplace platform, maybe it would be a better approach to ask them about it

**Comment by borispoehland** [comment]
@tanghel could you please leave this issue open until I'm back from vacation?

I assume I know the problem: I uploaded the metadata via IPFS desktop, and it looks like it didn't propagate the metadata to public nodes other than my computer.

So I HOPE that once I turn my computer and IPFS Desktop back on after my vacation, I manage to "publish" the metadata files to the whole network.

I'm not sure if Elrond will then **automatically** pick up and index my files, or if a **manual** indexing from your side will be required.

I will keep you updated, thanks for now!

**Comment by tanghel** [comment]
Hi @borispoehland !

We have merged a PR (https://github.com/ElrondNetwork/api.elrond.com/pull/694) which enables any collection owner to trigger regenerate of media / metadata

**Comment by borispoehland** [comment]
Hey @tanghel, can you please provide us with assistance on how to call this endpoint? We saw that you have to send a JWT called `address` with the request, but we don't exactly know how to create it. Thanks

**Comment by borispoehland** [comment]
@tanghel on another note, we now have our folder pinned to Pinata so that it's available even when my local node is down:
-  https://ipfs.io/ipfs/QmVjKGquME6MS3pMBTUovsGHVr86UVWnRveysFyHNeBUdQ

Would it be possible that you re-trigger the indexing of our metadata (this time)?
Our collection identifier is [SEAGULL-9746cc](https://explorer.elrond.com/collections/SEAGULL-9746cc)
