### ISSUE TITLE
How to refresh metadata using "address" JWT?

### ISSUE THREAD

**Issue by borispoehland** [ElrondNetwork/api.elrond.com#722]
Hello guys,

You recently implemented an endpoint `post nfts/process` to trigger metadata regeneration, thanks for that (https://github.com/ElrondNetwork/api.elrond.com/pull/694).

Could you provide me with assistance on how to use it? I saw that a JWT called `address` is involved and I can't really wrap my head around how to use it.

Our collection ticker is `SEAGULL-9746cc`, if **you** could trigger the regeneration one more time for us, that'd be great!

Best and thanks in advance,
Boris

**Comment by tanghel** [comment]
Hello & sorry for the delayed answer!

You need to log into the webwallet, and you will find in the local storage a jwt for your given session
<img width="977" alt="image" src="https://user-images.githubusercontent.com/4201606/180429517-8115ab3b-b39c-4507-b76a-fbc9227145ed.png">

Use that jwt as header for the following request:
Request: `POST https://api.elrond.com/nfts/process`
Header: `Authorization: Bearer <jwt>`
Body: `{ "collection": "SEAGULL-9746cc" }`
