### ISSUE TITLE
[Bug]: Difference between responses for /transactions /account/transactions

### ISSUE THREAD

**Issue by bogdanIuga** [ElrondNetwork/api.elrond.com#784]
### Contact Details

iugabogdan13@gmail.com

### Description

Different responses for the same entity

### Steps to reproduce

1. we're catching transactions for a specific address by calling https://api.elrond.com/transactions?status=success&withOperations=true every 6 seconds.
2. this is the response from /transactions:
![image](https://user-images.githubusercontent.com/26706013/185081667-aa594660-11e2-4c11-a549-d8d944f73ebb.png)

and this is the response from /account/transactions (https://api.elrond.com/accounts/erd1793tlju2h2ps3f5klqy3rkyj88h9njgx40ys5pkyz0cufhecxhrsenyyam/transactions?withOperations=true):
`{
    "txHash": "a75a9edacd2b2cae36d08d74edc33065db914040973ba2e5dd7def752e23b27a",
    "gasLimit": 8000000,
    "gasPrice": 1000000000,
    "gasUsed": 5450002,
    "miniBlockHash": "76052d00cf70f93cbad3c184d02b71ed88a411eac52394f20ce072382f021230",
    "nonce": 1553,
    "receiver": "erd1793tlju2h2ps3f5klqy3rkyj88h9njgx40ys5pkyz0cufhecxhrsenyyam",
    "receiverShard": 1,
    "round": 10768207,
    "sender": "erd1793tlju2h2ps3f5klqy3rkyj88h9njgx40ys5pkyz0cufhecxhrsenyyam",
    "senderShard": 1,
    "signature": "f3ec774367b3b1ef88ee37a5a62185d17d8e0497aa2151b7f2360d05835661e39d25be8925a481b80cf19c7dc33b90fb08ed02aba9537d69a6e4e1e22d631200",
    "status": "success",
    "value": "0",
    "fee": "371300020000000",
    "timestamp": 1660726842,
    "data": "RVNEVE5GVFRyYW5zZmVyQDRjNGI0ZDQ1NTgyZDYxNjE2MjM5MzEzMEA0MDY5NTNAMGM0ZTA0NTdjNzQ4ZGVhNDIwMDBAMDAwMDAwMDAwMDAwMDAwMDA1MDBlYmFkYjUyZmU0MjBiNGM1YTFlYTRlMDc0NzNkNGQyNjY0MTM5MDZlNzkwZUA2NjY5NmM2YzVmNmY2NjY2NjU3MjVmNzA2MTcyNzQ2OTYxNmNAMDJjODQwQDBh",
    "function": "fill_offer_partial",
    "action": {
      "category": "esdtNft",
      "name": "transfer",
      "description": "Transfer",
      "arguments": {
        "transfers": [
          {
            "type": "MetaESDT",
            "name": "LockedMEX",
            "ticker": "LKMEX",
            "svgUrl": "https://media.elrond.com/tokens/asset/LKMEX-aab910/logo.svg",
            "collection": "LKMEX-aab910",
            "decimals": 18,
            "identifier": "LKMEX-aab910-406953",
            "value": "58107556770000000000000"
          }
        ],
        "receiver": "erd1qqqqqqqqqqqqqpgqawkm2tlyyz6vtg02fcr5w02dyejp8yrw0y8qlucnj2",
        "functionName": "fill_offer_partial",
        "functionArgs": [
          "02c840",
          "0a"
        ],
        "receiverAssets": {
          "name": "JEXchange: P2P swaps module",
          "tags": [
            "jexchange",
            "swap"
          ]
        }
      }
    },
    "**operations**": [
      {
        "id": "4d092de97fcc176fd05c621c1b8b4e1863f2afcf61e267e4b16955aa3db01075",
        "action": "writeLog",
        "type": "log",
        "sender": "erd1793tlju2h2ps3f5klqy3rkyj88h9njgx40ys5pkyz0cufhecxhrsenyyam",
        "receiver": "erd1793tlju2h2ps3f5klqy3rkyj88h9njgx40ys5pkyz0cufhecxhrsenyyam",
        "data": "@6f6b"
      },
      {
        "id": "a75a9edacd2b2cae36d08d74edc33065db914040973ba2e5dd7def752e23b27a",
        "action": "transfer",
        "type": "nft",
        "esdtType": "MetaESDT",
        "collection": "LKMEX-aab910",
        "identifier": "LKMEX-aab910-406953",
        "name": "LockedMEX",
        "sender": "erd1793tlju2h2ps3f5klqy3rkyj88h9njgx40ys5pkyz0cufhecxhrsenyyam",
        "receiver": "erd1qqqqqqqqqqqqqpgqawkm2tlyyz6vtg02fcr5w02dyejp8yrw0y8qlucnj2",
        "value": "58107556770000000000000",
        "decimals": 18,
        "svgUrl": "https://media.elrond.com/tokens/asset/LKMEX-aab910/logo.svg"
      },
      {
        "id": "094483285a893eb0d894cc27cd0f75e70986a3a6b5ae6b0e0d62c4f05c9b23d5",
        "action": "writeLog",
        "type": "log",
        "sender": "erd1272et87h3sa7hlg5keuswh50guz2ngmd6lhmjxkwwu0ah6gdds5qhka964",
        "receiver": "erd1793tlju2h2ps3f5klqy3rkyj88h9njgx40ys5pkyz0cufhecxhrsenyyam",
        "data": "@6f6b"
      },
      {
        "id": "49895d26fa4cc73043122ebdc2a6d00f3c7dd3ee20cbaa02ef4dad383d977bf8",
        "action": "writeLog",
        "type": "log",
        "sender": "erd1272et87h3sa7hlg5keuswh50guz2ngmd6lhmjxkwwu0ah6gdds5qhka964",
        "receiver": "erd1793tlju2h2ps3f5klqy3rkyj88h9njgx40ys5pkyz0cufhecxhrsenyyam",
        "data": "@6f6b"
      },
      {
        "id": "a959ea9ca4ff52c2c02047af0820c6aa2c97209b57b8baa4a7acac3f1988a185",
        "action": "writeLog",
        "type": "log",
        "sender": "erd1nu5d78erc8fcefzlnwcn2njla6zuxk3emmalyy5xk5dukucfpt0sp5sycf",
        "receiver": "erd1793tlju2h2ps3f5klqy3rkyj88h9njgx40ys5pkyz0cufhecxhrsenyyam",
        "data": "@6f6b"
      },
      {
        "id": "b04b109673bbf866e87fed33eb7904774afeeaffd6a89b02a29dee7c5e2c00c7",
        "action": "transfer",
        "type": "esdt",
        "esdtType": "FungibleESDT",
        "identifier": "JEX-9040ca",
        "name": "JEX",
        "sender": "erd1qqqqqqqqqqqqqpgqawkm2tlyyz6vtg02fcr5w02dyejp8yrw0y8qlucnj2",
        "receiver": "erd1272et87h3sa7hlg5keuswh50guz2ngmd6lhmjxkwwu0ah6gdds5qhka964",
        "value": "514377900000000000",
        "decimals": 18,
        "svgUrl": "https://media.elrond.com/tokens/asset/JEX-9040ca/logo.svg"
      },
      {
        "id": "b04b109673bbf866e87fed33eb7904774afeeaffd6a89b02a29dee7c5e2c00c7",
        "action": "transfer",
        "type": "nft",
        "esdtType": "MetaESDT",
        "collection": "LKMEX-aab910",
        "identifier": "LKMEX-aab910-406953",
        "name": "LockedMEX",
        "sender": "erd1qqqqqqqqqqqqqpgqawkm2tlyyz6vtg02fcr5w02dyejp8yrw0y8qlucnj2",
        "receiver": "erd1272et87h3sa7hlg5keuswh50guz2ngmd6lhmjxkwwu0ah6gdds5qhka964",
        "value": "174322670310000000000",
        "decimals": 18,
        "svgUrl": "https://media.elrond.com/tokens/asset/LKMEX-aab910/logo.svg"
      },
      {
        "id": "b04b109673bbf866e87fed33eb7904774afeeaffd6a89b02a29dee7c5e2c00c7",
        "action": "transfer",
        "type": "esdt",
        "esdtType": "FungibleESDT",
        "identifier": "JEX-9040ca",
        "name": "JEX",
        "sender": "erd1qqqqqqqqqqqqqpgqawkm2tlyyz6vtg02fcr5w02dyejp8yrw0y8qlucnj2",
        "receiver": "erd1793tlju2h2ps3f5klqy3rkyj88h9njgx40ys5pkyz0cufhecxhrsenyyam",
        "value": "170944922100000000000",
        "decimals": 18,
        "svgUrl": "https://media.elrond.com/tokens/asset/JEX-9040ca/logo.svg"
      },
      {
        "id": "b04b109673bbf866e87fed33eb7904774afeeaffd6a89b02a29dee7c5e2c00c7",
        "action": "transfer",
        "type": "nft",
        "esdtType": "MetaESDT",
        "collection": "LKMEX-aab910",
        "identifier": "LKMEX-aab910-406953",
        "name": "LockedMEX",
        "sender": "erd1qqqqqqqqqqqqqpgqawkm2tlyyz6vtg02fcr5w02dyejp8yrw0y8qlucnj2",
        "receiver": "erd1nu5d78erc8fcefzlnwcn2njla6zuxk3emmalyy5xk5dukucfpt0sp5sycf",
        "value": "57933234099690000000000",
        "decimals": 18,
        "svgUrl": "https://media.elrond.com/tokens/asset/LKMEX-aab910/logo.svg"
      }
    ]
  },`

![image](https://user-images.githubusercontent.com/26706013/185081209-f1e800fb-c645-4518-818c-1df2a199a8a7.png)

Operations count is different for the same entity on 2 different endpoints

### On which network is the bug manifesting itself?

Mainnet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanghel** [comment]
The problem you are experiencing here is a timing issue.

In the first call, the transaction has status pending because it hasn't finished processing yet.

If at the same time the request would be performed on the account endpoint, the status would still be pending.

If you for example send a cross-shard transaction from one account to another, for ~ 24 seconds, the transaction will have status "pending". After the transaction reaches its intended destination, it will change its status to success or failed. 
If the receiver is a smart contract, it might send value or tokens back to the original sender, thus reaching the status "success" from a blockchain transfer perspective, but it will still have status "pending" from a smart contract execution perspective, since the transaction is not yet fully finalized. The API changes the status from "success" to "pending" in this particular situation.

Hope this further clarifies the current state of affairs 🙂

**Comment by tanghel** [comment]
For as long as the transaction has status "pending" when filtering by "success", it means it may still receive logs or smart contract results

**Comment by tanghel** [comment]
Will close this issue since we already have an open related issue
