### ISSUE TITLE
[Bug]: Providers endpoint differences

### ISSUE THREAD

**Issue by bogdanIuga** [ElrondNetwork/api.elrond.com#790]
### Contact Details

iugabogdan13@gmail.com

### Description

Differences between the same endpoint

### Steps to reproduce

1. go to [explorer.elrond.com ](https://explorer.elrond.com/providers)
2. check the response from https://internal-api.elrond.com/providers , 9th position (ArcStake)
3. "identity" is on the response

![image](https://user-images.githubusercontent.com/26706013/186095365-0465b13e-bf7e-41e8-ab6b-956522016cef.png)

1. go to https://api.elrond.com/#/providers/ProviderController_getProviders
2. check the response from https://api.elrond.com/providers
3. "identity" is not on the response for the same address 

![image](https://user-images.githubusercontent.com/26706013/186096379-7fb2b87b-39c5-45e7-b230-b4826299630d.png)

! it does not happen for all providers. for others, identity is coming as expected (8th position: mgstaking or 10th position: cslabsio works ok on both endpoints)

### On which network is the bug manifesting itself?

Mainnet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanghel** [comment]
hello!

it could have been a temporary glitch, it seems to work fine now.

We have separated internal from external infrastructure in the period of time you noticed that and it could have been that the caches were not fully warm at that point in time

**Comment by bogdanIuga** [comment]
yes, it works ok now.

Thanks for your answer!
