### ISSUE TITLE
[Feature Request]: Provide documentation for the /query endpoint

### ISSUE THREAD

**Issue by borispoehland** [ElrondNetwork/api.elrond.com#800]
### Describe the solution you'd like

Hello!

Looking at the [swagger docs of `/query`](https://api.elrond.com/#/query), there is no help as to how a successful request must look like.

Take the following endpoint as an example:
```
{
            "name": "stakeTime",
            "mutability": "readonly",
            "inputs": [
                {
                    "name": "address",
                    "type": "Address"
                }
            ],
            "outputs": [
                {
                    "type": "u64"
                }
            ]
        },
```

I want to be able to query this, so this is what I did:
```
POST https://devnet-api.elrond.com/query
Body: 
{
  "scAddress": "erd1qqqqqqqqqqqqqpgq30q49r76k220t9esf2fe089zs0swczp06ppst27q8z",
  "funcName": "stakeTime",
  "args": ["26a50f8d743d6ee3605655d83c8a150e567f163a5ac1711b51fec4e820e8db95"]
}
```

I get the following response:
```
{
  "returnData": [
    ""
  ],
  "returnCode": "ok",
  "gasRemaining": 18446744073707106000,
  "gasRefund": 0,
  "outputAccounts": {
    "000000000000000005008bc1528fdab294f597304a93979ca283e0ec082fd043": {
      "address": "erd1qqqqqqqqqqqqqpgq30q49r76k220t9esf2fe089zs0swczp06ppst27q8z",
      "nonce": 0,
      "balanceDelta": 0,
      "storageUpdates": {},
      "callType": 0
    }
  }
}
```
whereas the `returnData` is empty. 

Please advise me on how to call the `/query` endpoint. Is it also possible to get results in `struct` format? For instance, let's say my endpoint would return this struct:
```
"StakedNftsUserResult": {
            "type": "struct",
            "fields": [
                {
                    "name": "pending_rewards",
                    "type": "BigUint"
                },
                {
                    "name": "total_daily_reward",
                    "type": "BigUint"
                },
                {
                    "name": "staked_nfts",
                    "type": "List<EsdtTokenPayment>"
                }
            ]
        }
```

Would it be possible then to query this via REST?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanghel** [comment]
Hello!

You can find in the Elrond documentation details about how to use the vm query functions:
https://docs.elrond.com/sdk-and-tools/rest-api/virtual-machine/

Regarding deserializing the results back, you can take a look at the Elrond serialization format specs:
https://docs.elrond.com/developers/developer-reference/elrond-serialization-format/

Furthermore, you can use `erdjs` to more easily interact with the vm queries, based on the smart contract's ABI, if you have acccess to it:
https://docs.elrond.com/sdk-and-tools/erdjs/writing-and-testing-erdjs-interactions/
