### ISSUE TITLE
[Bug]: /transactions withScamInfo required

### ISSUE THREAD

**Issue by bogdanIuga** [ElrondNetwork/api.elrond.com#804]
### Contact Details

iugabogdan13@gmail.com

### Description

false mandatory on Swagger

### Steps to reproduce

1. go to https://api.elrond.com/#/transactions/TransactionController_getTransactions
2. withScamInfo is marked as required, and execution is not possible without setting it to true/false
3. make a request to the API without the withScamInfo parameter: https://api.elrond.com/transactions?size=25 from the browser/postman and it will work

### On which network is the bug manifesting itself?

Mainnet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanghel** [comment]
fixed in https://github.com/ElrondNetwork/api.elrond.com/pull/808
