### ISSUE TITLE
[Bug]: Problem fetching Smart Contract Results after issuance of SFT/NFT

### ISSUE THREAD

**Issue by AurelienVasseur** [ElrondNetwork/api.elrond.com#870]
### Contact Details

aurelienvasseur60@gmail.com

### Description

'SmartContractResults' missing from the GET transaction endpoint

### Steps to reproduce

As mentioned in the documentation (https://docs.elrond.com/tokens/nft-tokens/#example-flow) we must be allowed to fetch to Token Identifier but the API (endpoint https://gateway.elrond.com/transaction/*txHash*?withResults=true) does not return the 'smartContractResults' anymore.

Previously it was perfectly working but it seems like some tiny things have changed in the documentation (https://docs.elrond.com/tokens/esdt-tokens/#parse-fungible-tokens-transfer-logs).

So my question is: How can we get the 'smartContractResults' informations? (the objective is to get the nonce of the created SFT/NFT)

Request:  https://devnet-gateway.elrond.com/transaction/:txHash?withResults=true

With Tx Hash: 9477bcbba7dbee948afef6c21d67a2409f61e3dc9ea84a94c708fd4760b60ae2

### On which network is the bug manifesting itself?

Devnet

### Relevant log output

```shell
{
    "data": {
        "transaction": {
            "type": "normal",
            "processingTypeOnSource": "BuiltInFunctionCall",
            "processingTypeOnDestination": "BuiltInFunctionCall",
            "hash": "9477bcbba7dbee948afef6c21d67a2409f61e3dc9ea84a94c708fd4760b60ae2",
            "nonce": 492,
            "round": 0,
            "epoch": 0,
            "value": "0",
            "receiver": "erd1xk7eu7jj3rldfaq5hvxfwywry6v2m2zkr9q7ak00wc459n3m60ws7jvg2d",
            "sender": "erd1xk7eu7jj3rldfaq5hvxfwywry6v2m2zkr9q7ak00wc459n3m60ws7jvg2d",
            "gasPrice": 1000000000,
            "gasLimit": 3606000,
            "data": "RVNEVE5GVENyZWF0ZUA1MzU0NDU1MzU0MzMyZDMxMzgzMTM5MzczOUAwZjQyNDBANTQ2NTczNzQyMDMyMzFAMDAwMEAwMEA2ZDY1NzQ2MTY0NjE3NDYxM2E2ODc0NzQ3MDczM2EyZjJmNjk3MDY2NzMyZTY5NmYyZjY5NzA2NjczMmY1MTZkNjQzODYxMzc3MzZiNjk1OTcxNTYzNzZmNmE0MzU1NzE1ODMyNjY0Mzc3Mzg0YzM4NzE1Mjc5MzIzMjQzNzM0NTRhNTI3MDY2NTk1MTUzNDM0NDQ3NjUzOTNiNzQ2MTY3NzMzYTc0NjE2NzIwMzEyYzc0NjE2NzIwMzIyYzc0NjE2NzIwMzNANjg3NDc0NzA3MzNhMmYyZjY5NzA2NjczMmU2OTZmMmY2OTcwNjY3MzJmNTE2ZDVhMzc0YjY3NDg0ODMzNGU0YTZiNDE3NTQ0NjU2ODM4MzY1NTZkNjczNDcwNzg3Mzc4NWEzNjRkNDg0NjY1NDE2YTRiNDc0YzQ0NzQ2NDU2NzgzMjY2Njc=",
            "signature": "a3f68a0b69d0da49141a1cfb902c614074905e52800fbb8ec90fc21bf5d725fe8f1c2bd4c2925f0fcb11642dac4a572e8a6d56d42df83a05a1bd03ef37c90e0b",
            "sourceShard": 0,
            "destinationShard": 0,
            "status": "success",
            "tokens": [
                "STEST3-181979"
            ],
            "esdtValues": [
                "1000000"
            ],
            "operation": "ESDTNFTCreate",
            "initiallyPaidFee": "3606000000000000"
        }
    },
    "error": "",
    "code": "successful"
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanghel** [comment]
Hello!

We have indeed a temporary issue on the devnet gateway. 

The issue should be solved within the next hour, so that the issuance scr should be available on the documented endpoint

**Comment by tanghel** [comment]
Alternatively, you can also find the log for the `ESDTNFTCreate` in the transaction details in the api endpoint:

https://devnet-api.elrond.com/transactions/9477bcbba7dbee948afef6c21d67a2409f61e3dc9ea84a94c708fd4760b60ae2

**Comment by AurelienVasseur** [comment]
Thanks for your feedback you solved my problem!

**Comment by tanghel** [comment]
The temporary issue has been fixed in the meantime

The logs are now also available at https://devnet-gateway.elrond.com/transaction/9477bcbba7dbee948afef6c21d67a2409f61e3dc9ea84a94c708fd4760b60ae2?withResults=true
